In [17]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np,gc # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sn
import matplotlib.pyplot as plt
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/organizations/new-york-city/nyc-parking-tickets/Parking_Violations_Issued_-_Fiscal_Year_2017.csv
/kaggle/input/datasets/organizations/new-york-city/nyc-parking-tickets/Parking_Violations_Issued_-_Fiscal_Year_2016.csv
/kaggle/input/datasets/organizations/new-york-city/nyc-parking-tickets/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv
/kaggle/input/datasets/organizations/new-york-city/nyc-parking-tickets/Parking_Violations_Issued_-_Fiscal_Year_2015.csv

# Import Dataset

In [9]:
file_path = '/kaggle/input/datasets/organizations/new-york-city/nyc-parking-tickets/Parking_Violations_Issued_-_Fiscal_Year_2017.csv'
df_2017 = pd.read_csv(file_path, low_memory=False)
df_2017.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,5092469481,GZH7067,NY,PAS,07/10/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
1,5092451658,GZH7067,NY,PAS,07/08/2016,7,SUBN,TOYOT,V,0,...,GY,NaN,2001,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN
2,4006265037,FZX9232,NY,PAS,08/23/2016,5,SUBN,FORD,V,0,...,BK,NaN,2004,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
3,8478629828,66623ME,NY,COM,06/14/2017,47,REFG,MITSU,T,10610,...,WH,NaN,2007,NaN,0,04,47-Double PKG-Midtown,NaN,NaN,NaN
4,7868300310,37033JV,NY,COM,11/21/2016,69,DELV,INTER,T,10510,...,WHITE,NaN,2007,NaN,0,31 6,69-Failure to Disp Muni Recpt,NaN,NaN,NaN

The device only can run a dataset (2015,2016, or 2017)

In [10]:
#df_2015 = pd.read_csv('/kaggle/input/datasets/organizations/new-york-city/nyc-parking-tickets/Parking_Violations_Issued_-_Fiscal_Year_2015.csv',low_memory=False)
#df_2016 = pd.read_csv('/kaggle/input/datasets/organizations/new-york-city/nyc-parking-tickets/Parking_Violations_Issued_-_Fiscal_Year_2016.csv',low_memory=False)

In [11]:
df_zero_null_columns_2017=df_2017.dropna(axis=1, how='all')
df_zero_null_columns_2017.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Days Parking In Effect,From Hours In Effect,To Hours In Effect,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description
0,5092469481,GZH7067,NY,PAS,07/10/2016,7,SUBN,TOYOT,V,0,...,NaN,NaN,NaN,GY,NaN,2001,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT
1,5092451658,GZH7067,NY,PAS,07/08/2016,7,SUBN,TOYOT,V,0,...,NaN,NaN,NaN,GY,NaN,2001,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT
2,4006265037,FZX9232,NY,PAS,08/23/2016,5,SUBN,FORD,V,0,...,NaN,NaN,NaN,BK,NaN,2004,NaN,0,NaN,BUS LANE VIOLATION
3,8478629828,66623ME,NY,COM,06/14/2017,47,REFG,MITSU,T,10610,...,Y,0700A,0700P,WH,NaN,2007,NaN,0,04,47-Double PKG-Midtown
4,7868300310,37033JV,NY,COM,11/21/2016,69,DELV,INTER,T,10510,...,Y,0700A,0700P,WHITE,NaN,2007,NaN,0,31 6,69-Failure to Disp Muni Recpt

In [12]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10803028 entries, 0 to 10803027
Data columns (total 43 columns):
 #   Column                             Dtype
---  ------                             -----
 0   Summons Number                     int64
 1   Plate ID                           object
 2   Registration State                 object
 3   Plate Type                         object
 4   Issue Date                         object
 5   Violation Code                     int64
 6   Vehicle Body Type                  object
 7   Vehicle Make                       object
 8   Issuing Agency                     object
 9   Street Code1                       int64
 10  Street Code2                       int64
 11  Street Code3                       int64
 12  Vehicle Expiration Date            int64
 13  Violation Location                 float64
 14  Violation Precinct                 int64
 15  Issuer Precinct                    int64
 16  Issuer Code                        int64
 17  Issuer Command                     object
 18  Issuer Squad                       object
 19  Violation Time                     object
 20  Time First Observed                object
 21  Violation County                   object
 22  Violation In Front Of Or Opposite  object
 23  House Number                       object
 24  Street Name                        object
 25  Intersecting Street                object
 26  Date First Observed                int64
 27  Law Section                        int64
 28  Sub Division                       object
 29  Violation Legal Code               object
 30  Days Parking In Effect             object
 31  From Hours In Effect               object
 32  To Hours In Effect                 object
 33  Vehicle Color                      object
 34  Unregistered Vehicle?              float64
 35  Vehicle Year                       int64
 36  Meter Number                       object
 37  Feet From Curb                     int64
 38  Violation Post Code                object
 39  Violation Description              object
 40  No Standing or Stopping Violation  float64
 41  Hydrant Violation                  float64
 42  Double Parking Violation           float64
dtypes: float64(5), int64(13), object(25)
memory usage: 3.5+ GB

In [13]:
df_2017.shape[0]

10803028

In [14]:
df_2017.shape[1]

43

# EDA

## NaN Identification
We will explore this 2017 dataset to calculate NaN values inside each columns.

In [16]:
nan_df = df_2017.isna()
nans_gr = {}
for col in df_2017.columns:
    current_nan = nan_df[col].sum()
    try:
        nans_gr[current_nan].append(col)
    except:
        nans_gr[current_nan]=[col]
del nan_df; x=gc.collect()

for k,v in nans_gr.items():
    print('####### NAN count =',k)
    print(v)

####### NAN count = 0
['Summons Number', 'Registration State', 'Plate Type', 'Issue Date', 'Violation Code', 'Issuing Agency', 'Street Code1', 'Street Code2', 'Street Code3', 'Vehicle Expiration Date', 'Violation Precinct', 'Issuer Precinct', 'Issuer Code', 'Date First Observed', 'Law Section', 'Vehicle Year', 'Feet From Curb']
####### NAN count = 728
['Plate ID']
####### NAN count = 42711
['Vehicle Body Type']
####### NAN count = 73050
['Vehicle Make']
####### NAN count = 2072400
['Violation Location']
####### NAN count = 2062645
['Issuer Command']
####### NAN count = 2063541
['Issuer Squad']
####### NAN count = 63
['Violation Time']
####### NAN count = 9962281
['Time First Observed']
####### NAN count = 39547
['Violation County']
####### NAN count = 2161235
['Violation In Front Of Or Opposite']
####### NAN count = 2288618
['House Number']
####### NAN count = 4009
['Street Name']
####### NAN count = 7435473
['Intersecting Street']
####### NAN count = 773
['Sub Division']
####### NAN count = 8740321
['Violation Legal Code']
####### NAN count = 2712416
['Days Parking In Effect    ']
####### NAN count = 5450946
['From Hours In Effect']
####### NAN count = 5450943
['To Hours In Effect']
####### NAN count = 152342
['Vehicle Color']
####### NAN count = 9675432
['Unregistered Vehicle?']
####### NAN count = 9017555
['Meter Number']
####### NAN count = 3190187
['Violation Post Code']
####### NAN count = 1127470
['Violation Description']
####### NAN count = 10803028
['No Standing or Stopping Violation', 'Hydrant Violation', 'Double Parking Violation']

In [20]:
nan_df_2017 = df_2017.isna()
top_10_NaN = {}
for col in df_2017.columns:
    current_nan = nan_df_2017[col].sum()
    try:
        top_10_NaN[current_nan].append(col)
    except:
        top_10_NaN[current_nan]=[col]

top_10_NaN = dict(sorted(top_10_NaN.items(), key=lambda item: item[1]))

#Bar Chart 10 most NaN features
sn.barplot(x='feature',y='NaN Counts')

plt.show()

ValueError: Could not interpret value `feature` for `x`. An entry with this name does not appear in `data`.